runtime: nodejs10
env: standard

env_variables: 
  DOMAIN: "www.[SAMPLE_COMPANY].com/"
  PROTOCOL: "https://"
  IP: "[SAMPLE_COMPANY]app.herokuapp.com/"
  PORT: "8080"
  NODE_ENV: "production"
  MONGOLAB_URI: "mongodb://mr_amoaddai:[SAMPLE_COMPANY]2019@ds259787.mlab.com:59787/[SAMPLE_COMPANY]"
  SECRET_SESSION: "[SAMPLE_COMPANY]-secret"
